### ISSUE TITLE
代码风格问题

### ISSUE THREAD

**Issue by zero6six** [Mzcczycle/Temperature-transformer#2]
注释符号 # 后应保留一个空格。
另外为什么第一个 if 用 list，第二个用 set?

**Comment by Mzcczycle** [comment]
thanks for your comment， 
for另外 ： 我不到啊...W我两个if不一样吗？

**Comment by zero6six** [comment]
if TempStr[-1] in ['F','f']:
和 in {'C','c'}

**Comment by TOM1007** [comment]
缩进空格数也不统一

**Comment by Mzcczycle** [comment]
if TempStr[-1] in ['F','f']:

if TempStr[-1] in {'C','c'}:
it is not the same?

**Comment by Mzcczycle** [comment]
哦，我日
打错括号了

**Comment by Mzcczycle** [comment]
上面是列表的，下面大括号是什么来着...

**Comment by zero6six** [comment]
[] 声明 list，{} 声明 set。
另：英文的","后面往往要打一个空格，运算符和变量间往往也要打空格。

**Comment by zero6six** [comment]
还有 github 的 Comment 不要整的和 QQ 一样，能一个 Comment 发完的内容最好一次发完。

**Comment by Mzcczycle** [comment]
i know

**Comment by zero6six** [comment]
Issue 为什么要我自己关啊（恼）
